lenguage: node_js
cache:
  directories: 
    -~!@/.npm
node_js:
  - '12'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB-TOKEN-MSF
  local-dir: /dist
  target-branch: master
  commit_message: "Deploy realase ${TRAVIS_TAG}"
  on:
    branch: master